---
abstract: 'Computes the Cosine Similarity'
author:
  - 'Antoine Imbert <antoine.imbert@gmail.com>'
build_requires:
  Math::Trig: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-CosineSimilarity
provides:
  Data::CosineSimilarity:
    file: lib/Data/CosineSimilarity.pm
    version: 0.01
  Data::CosineSimilarity::Result:
    file: lib/Data/CosineSimilarity.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
